name: CI-Maven

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      jdk:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK ${{ inputs.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.jdk }}
#          distribution: temurin
          distribution: dragonwell
          cache: maven
      - name: Build
        timeout-minutes: 360
        run: |
          ./mvnw clean package -DskipTests -T 1C -pl \
          taier-data-develop,\
          taier-common,\
          taier-worker/taier-worker-plugin,\
          taier-datasource/taier-datasource-plugin \
          -am -amd
