name: CI-Web

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    env:
      working-directory: ./taier-ui
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: pnpm

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: pnpm install

      - name: Run build
        working-directory: ${{ env.working-directory }}
        run: pnpm build

      - name: Run tests
        working-directory: ${{ env.working-directory }}
        run: pnpm test
        env:
          CI: true
          NODE_ENV: test