name: CI

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 20 * * *' # automatic test while every day on 04:00 am at UTC+10

jobs:
  build_maven:
    if: github.repository == 'kalencaya/Taier'
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 8 ]
    uses: ./.github/workflows/ci-maven.yml
    with:
      os: ${{ matrix.os }}
      jdk: ${{ matrix.jdk }}
  build_web:
    if: github.repository == 'kalencaya/Taier'
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    uses: ./.github/workflows/ci-web.yml
    with:
      os: ${{ matrix.os }}
  build_docker:
    if: github.repository == 'kalencaya/Taier'
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 8 ]
        image: [ taier-mysql, taier, taier-ui ]
    uses: ./.github/workflows/ci-docker.yml
    with:
      os: ${{ matrix.os }}
      jdk: ${{ matrix.jdk }}
      push: false
      image: ${{ matrix.image }}
      registry: ghcr.io
      repository: ${{ github.repository }}
    secrets:
      HUB_USERNAME: ${{ github.actor }}
      HUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}